# ==========================================================
#   world-fusion (bm2cp × where2comm)   –   training config
# ----------------------------------------------------------
#   • opv2v:   keep paths as-is
#   • v2x-sim: change root_dir / validate_dir / test_dir
# ==========================================================

name: worldfusion_v2xsim_det

# ---------- data -------------------------------------------------------------
root_dir:       "data/v2xsim2_info/v2xsim_infos_train.pkl"
validate_dir:   "data/v2xsim2_info/v2xsim_infos_val.pkl"
test_dir:       "data/v2xsim2_info/v2xsim_infos_test.pkl"

yaml_parser:    "load_cross_modal_point_pillar_params"

train_params:
  batch_size:   16
  epoches:      30
  eval_freq:    2
  save_freq:    3
  max_cav:      5

noise_setting:
  add_noise: true
  args:
    pos_std: 0.2
    rot_std: 0.2
    pos_mean: 0
    rot_mean: 0

comm_range: 70

input_source:     ['lidar','camera','depth']
label_type:       'lidar'

# FIX: Define the world canvas range here to be reused everywhere.
world_lidar_range: &world_range [-100, -100, -3, 100, 100, 1]
# Keep the original ego-centric range for backward compatibility if needed elsewhere.
cav_lidar_range: &cav_range [-140.8,-38.4,-3, 140.8,38.4,1]

# ---------- pre-process ------------------------------------------------------
preprocess:
  core_method:  'SpVoxelPreprocessor'
  # FIX: Moved cav_lidar_range here to satisfy the yaml_parser script.
  cav_lidar_range: *world_range 
  args:
    voxel_size:           &voxel_size [0.78125, 0.78125, 4]
    max_points_per_voxel: 32
    max_voxel_train:      32000
    max_voxel_test:       70000
    # FIX: Kept a copy here for the preprocessor module itself.
    cav_lidar_range: *world_range

# ---------- fusion (dataset side) -------------------------------------------
fusion:
  core_method: 'LiDARCameraIntermediateFusionDatasetV2XSim'
  args:
    proj_first: True
    # FIX: Define a world-centric grid for camera BEV projection.
    grid_conf: &world_grid_conf
      xbound:  [-100, 100, 0.78125] # 200m / 0.5 res = 400 cells
      ybound:  [-100, 100, 0.78125]
      zbound:  [-10, 10, 20]
      ddiscr:  [2, 50, 48]
      mode:    'LID'
    data_aug_conf: &data_aug_conf
      resize_lim: [0.7, 0.8]
      final_dim:  [300, 400]
      rot_lim:    [0, 0]
      h: 600
      w: 800
      rand_flip:  False
      bot_pct_lim: [0.0,0.20]
      cams:    ['camera0','camera1','camera2','camera3']
      Ncams:   4

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]
  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]
  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# ---------- anchor / post-process -------------------------------------------
postprocess:
  core_method: 'WorldVoxelPostprocessor'
  gt_range: *world_range
  anchor_args:
    cav_lidar_range: *cav_range # keep for compatibility
    canvas_size_m: 200
    canvas_res: 0.78125
    # FIX: Removed redundant/incorrect w and h keys. They are calculated in code.
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    num: &anchor_num 2
    feature_stride: 4
  target_args:
    pos_threshold:   0.6
    neg_threshold:   0.45
    score_threshold: 0.2
  order:    'hwl'
  max_num: 150
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins:   2
    anchor_yaw: [0,90]

# ==========  model ===========================================================
model:
  core_method: point_pillar_worldfusion
  args:
    ####  shared with bm2cp  ####
    device:           cuda
    supervise_single: False
    backbone_fix:     False
    anchor_number:    *anchor_num
    outc:             256
    voxel_size:       *voxel_size
    lidar_range:      *world_range # FIX: The model must be aware of the world range.

    # --------------- camera branch ---------------
    img_params:
      grid_conf:          *world_grid_conf # FIX: Use the world grid for camera branch.
      data_aug_conf:      *data_aug_conf
      img_downsample:     8
      bev_dim:            64
      use_depth_gt:       False
      depth_supervision:  False

    # --------------- lidar branch ---------------
    pc_params:
      voxel_size: *voxel_size
      lidar_range: *world_range # FIX: Use the world range for the LiDAR branch.
      pillar_vfe:
        use_norm:         True
        with_distance:    False
        use_absolute_xyz: True
        num_filters:      [64]
      point_pillar_scatter:
        num_features:     64

    # --------------- block-level fusion ----------
    modality_fusion:
      bev_backbone:
        encode_first: False
        multi_scale:  True
        layer_nums:         [3,4,5]
        layer_strides:      [2,2,2]
        num_filters:        [64,128,256]
        upsample_strides:   [1,2,4]
        num_upsample_filter: [128,128,128]
        voxel_size:         *voxel_size

      shrink_header:
        use:        True
        input_dim:  384
        dim:        [256]
        kernal_size: [3]
        stride:      [2]
        padding:     [1]

      compression: 0

    # --------------- cooperative fusion (where2comm) ----
    fusion_args:
      fully:           false
      voxel_size:      *voxel_size
      downsample_rate: 4
      in_channels:     256
      multi_scale:     true      # This is correct and works with AttenFusion
      layer_nums:      [3,4,5]
      num_filters:     [64,128,256]
      communication:
        round: 1
        threshold: 0.01
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0
      agg_operator:
        mode: 'ATTEN'           # FIX: Revert to your original, correct choice
        feature_dim: 256
        multi_scale: true
        layer_nums: [3,4,5]
        num_filters: [64,128,256]

    # --------------- world canvas  -----------------------
    canvas_res:    0.5
    canvas_size_m: 200

    # --------------- dir-head (optional) ------------------
    dir_args: *dir_args

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg:        2.0

optimizer:
  core_method: Adam
  lr: 2e-4
  args:
    eps: 1e-10
    weight_decay: 1e-2

lr_scheduler:
  core_method: cosineannealwarm
  epoches:       50
  warmup_lr:     2e-5
  warmup_epoches: 5
  lr_min:        5e-6
